name: Deploy

on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/   
      - name: Install npm
        run: npm install
        run: npm run css:build
      - name: publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NOT_MARIO_UI_SECRET}}
